version: '3.8'

services:
  inner_api:
    build:
      context: ./inner_api
      dockerfile: Dockerfile.prod
    command: gunicorn rest_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/inner_api/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/inner_api/staticfiles
    ports:
      - 1337:80
    depends_on:
      - inner_api
volumes:
  static_volume:
